version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --init-file=/data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=app
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=rest_api_example
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    networks:
      - app

networks:
  app:
    name: app
